// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw5jUXevkoCjPFBLQtd5MbE1_0rhSihIM',
    appId: '1:882573394231:web:01380f08c0a132d8bc1ab2',
    messagingSenderId: '882573394231',
    projectId: 'rvm-db-84468',
    authDomain: 'rvm-db-84468.firebaseapp.com',
    storageBucket: 'rvm-db-84468.firebasestorage.app',
    measurementId: 'G-5YH7GEP8J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg2Yad3JKC6DrFlRGfbz7alfHEopui4W4',
    appId: '1:882573394231:android:21128429b1791dc0bc1ab2',
    messagingSenderId: '882573394231',
    projectId: 'rvm-db-84468',
    storageBucket: 'rvm-db-84468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSD60WVxz4Wpli4x9rtvSCFYwhS8w7uZ8',
    appId: '1:882573394231:ios:aed3b9a951ae8a49bc1ab2',
    messagingSenderId: '882573394231',
    projectId: 'rvm-db-84468',
    storageBucket: 'rvm-db-84468.firebasestorage.app',
    iosBundleId: 'com.example.rvmsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSD60WVxz4Wpli4x9rtvSCFYwhS8w7uZ8',
    appId: '1:882573394231:ios:aed3b9a951ae8a49bc1ab2',
    messagingSenderId: '882573394231',
    projectId: 'rvm-db-84468',
    storageBucket: 'rvm-db-84468.firebasestorage.app',
    iosBundleId: 'com.example.rvmsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw5jUXevkoCjPFBLQtd5MbE1_0rhSihIM',
    appId: '1:882573394231:web:17758881dc662a64bc1ab2',
    messagingSenderId: '882573394231',
    projectId: 'rvm-db-84468',
    authDomain: 'rvm-db-84468.firebaseapp.com',
    storageBucket: 'rvm-db-84468.firebasestorage.app',
    measurementId: 'G-G8LZM7JNHD',
  );
}
